### ISSUE TITLE
Add Countries 31-40

### ISSUE THREAD

**Issue by VectorChi** [VectorChi/worldpresidents#5]
The countries are

31. Cambodia
32. Cameroon
33. Canada
34. Central African Republic
35. Chad
36. Chile
37. China
38. Colombia
39. Comoros
40. Congo (Congo-Brazzaville)

Do check out https://www.worldometers.info/geography/alphabetical-list-of-countries/

**Comment by maddy020** [comment]
I like to work on this issue 
Please assign it to me

**Comment by VectorChi** [comment]
Done 👍🏽
