### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by VectorChi** [VectorChi/worldpresidents#53]
Should include Profile image, name, role, country, portfolio link, Github link

**Comment by agung2001** [comment]
hi @VectorChi 👋😄
I would like to take this issue, but I'm gonna need more detail.
which `contributors page` are you referring to?
- are you gonna create `contributors.html` consist of all the contributors?
- or you're going to create `CONTRIBUTORS.md` so it'll be accessible via GitHub only?

**Comment by VectorChi** [comment]
Hi @agung2001 Here, I meant contributors.html

**Comment by agung2001** [comment]
alright, if that's ok for you, I would like to create `contributors.html` page and add it to this repo via pull request (PR).
the content of that page will be using the same structure as `index.html` but with lists of contributors in it.
so what do you think?

**Comment by VectorChi** [comment]
Yeah. That works. Thanks

**Comment by agung2001** [comment]
hey @VectorChi 👋😄
I just finished creating the `contributors.html` page you can review it here : 
- #55 

just let me know if you had any questions, 
if that looks good you can then merge it 😄👍

**Comment by VectorChi** [comment]
Nice 👍🏽

**Comment by VectorChi** [comment]
Great work @agung2001

**Comment by agung2001** [comment]
ok, cheerio bro 😄🍻
